In [ ]:
import numpy as np
import pandas as pd

def f(t,y):
  return (2/t)*y + t**2 * np.exp(t)

#INPUT endpoints a, b; integer N; initial condition alpha
def euler(a, b, alpha, N):
  #set h, t and w
  h = (b-a)/N
  t = a
  w = alpha
  estimates = [(t,w)]
  for i in range(N):
    w = w + h * f(t,w) #compute w_i
    w = float(w)
    t = a + (i+1) * h #compute t_i
    estimates.append((t,w))
  return estimates

def y_exact(t):
  return t**2 * (np.exp(t) - np.exp(1))

In [ ]:
# Part (a) h = 0.1
estimates1 = euler(1,2,0,10)

chart = []
for t, w in estimates1:
    y_i = y_exact(t)
    error = abs(y_i - w)
    chart.append([t, w, y_i, error])

df = pd.DataFrame(chart, columns=["t_i", "w_i", "y_i", "|y_i - w_i|"])
df

    t_i        w_i        y_i  |y_i - w_i|
0   1.0   0.000000   0.000000     0.000000
1   1.1   0.271828   0.345920     0.074092
2   1.2   0.684756   0.866643     0.181887
3   1.3   1.276978   1.607215     0.330237
4   1.4   2.093548   2.620360     0.526812
5   1.5   3.187445   3.967666     0.780221
6   1.6   4.620818   5.720962     1.100144
7   1.7   6.466396   7.963873     1.497477
8   1.8   8.809120  10.793625     1.984505
9   1.9  11.747997  14.323082     2.575085
10  2.0  15.398236  18.683097     3.284861

In [ ]:

# Part (b): Linear interpolation for 1.04, 1.55, 1.97

# Euler with h = 0.1 → N = 10 for interval [1, 2]
estimates = euler(1, 2, 0, 10)

targets = [1.04, 1.55, 1.97]
results = []

for t_star in targets:
    # find the correct interval [t_i, t_{i+1}]
    for (t_i, w_i), (t_j, w_j) in zip(estimates[:-1], estimates[1:]):
        if t_i <= t_star <= t_j:
            # linear interpolation formula
            w_star = w_i + (t_star - t_i) / (t_j - t_i) * (w_j - w_i)
            y_true = y_exact(t_star)
            error = abs(y_true - w_star)
            results.append([t_star, w_star, y_true, error])
            break
df_partb = pd.DataFrame(results,
                        columns=["t", "Interpolated w(t)", "Exact y(t)", "Error"])
df_partb

      t  Interpolated w(t)  Exact y(t)     Error
0  1.04           0.108731    0.119987  0.011256
1  1.55           3.904131    4.788635  0.884504
2  1.97          14.303164   17.279298  2.976135

In [ ]:
# Part (c) Step Size Calculation

tolerance = 0.1
a, b = 1, 2

# Determine Lipschitz Constant L (L = max(|df/dy|))
def df_dy(t):
    return 2.0 / t
t_vals = np.linspace(a, b, 100)
L = max(df_dy(t) for t in t_vals)

# Determine M (M = max(|y''(t)|))
def y_double_prime_exact(t):
    return abs(np.exp(t) * (t**2 + 4*t + 2) - 2 * np.exp(1))

# Estimate M by finding the maximum value on [a, b]
M = max(y_double_prime_exact(t) for t in np.linspace(a, b, 1000))

# Compute h using the Euler error bound formula (Eq. 5.10)
numerator = 2 * L * tolerance
denominator = M * (np.exp(L * (b - a)) - 1)
h = numerator / denominator
print("Step size h for tolerance 0.1:", h)

Step size h for tolerance 0.1: 0.0006387808944412324

In [ ]:
# Part (a) Extra Task: h = 0.5
estimates2 = euler(1,2,0,20)

chart = []
for t, w in estimates2:
    y_i = y_exact(t)
    error = abs(y_i - w)
    chart.append([t, w, y_i, error])

df = pd.DataFrame(chart, columns=["t_i", "w_i", "y_i", "|y_i - w_i|"])
df

     t_i        w_i        y_i  |y_i - w_i|
0   1.00   0.000000   0.000000     0.000000
1   1.05   0.135914   0.153655     0.017741
2   1.10   0.306386   0.345920     0.039534
3   1.15   0.515992   0.581782     0.065791
4   1.20   0.769696   0.866643     0.096947
5   1.25   1.072886   1.206346     0.133460
6   1.30   1.431400   1.607215     0.175815
7   1.35   1.851563   2.076089     0.224527
8   1.40   2.340224   2.620360     0.280136
9   1.45   2.904792   3.248011     0.343219
10  1.50   3.553282   3.967666     0.414384
11  1.55   4.294358   4.788635     0.494277
12  1.60   5.137379   5.720962     0.583583
13  1.65   6.092453   6.775480     0.683027
14  1.70   7.170493   7.963873     0.793381
15  1.75   8.383272   9.298733     0.915461
16  1.80   9.743489  10.793625     1.050135
17  1.85  11.264837  12.463163     1.198326
18  1.90  12.962071  14.323082     1.361010
19  1.95  14.851090  16.390318     1.539228
20  2.00  16.949013  18.683097     1.734084

In [ ]:
# Part (d) Look at attached pdf
# Part (e) Extra Task: y(1) = 0.1
# unperturbed
estimates_unpert = euler(1, 2, 0, 20)

# perturbed initial condition
estimates_pert = euler(1, 2, 0.1, 20)

# compute differences
comparison = []
for ((t, w_unpert), (_, w_pert)) in zip(estimates_unpert, estimates_pert):
    diff = w_pert - w_unpert
    comparison.append([t, w_unpert, w_pert, diff])

df_diff = pd.DataFrame(comparison,
                       columns=["t", "w(t) with y(1)=0", "w(t) with y(1)=0.1", "difference"])
df_diff

       t  w(t) with y(1)=0  w(t) with y(1)=0.1  difference
0   1.00          0.000000            0.100000    0.100000
1   1.05          0.135914            0.245914    0.110000
2   1.10          0.306386            0.426862    0.120476
3   1.15          0.515992            0.647420    0.131429
4   1.20          0.769696            0.912553    0.142857
5   1.25          1.072886            1.227648    0.154762
6   1.30          1.431400            1.598543    0.167143
7   1.35          1.851563            2.031563    0.180000
8   1.40          2.340224            2.533557    0.193333
9   1.45          2.904792            3.111935    0.207143
10  1.50          3.553282            3.774711    0.221429
11  1.55          4.294358            4.530548    0.236190
12  1.60          5.137379            5.388807    0.251429
13  1.65          6.092453            6.359596    0.267143
14  1.70          7.170493            7.453826    0.283333
15  1.75          8.383272            8.683272    0.300000
16  1.80          9.743489           10.060632    0.317143
17  1.85         11.264837           11.599599    0.334762
18  1.90         12.962071           13.314929    0.352857
19  1.95         14.851090           15.222518    0.371429
20  2.00         16.949013           17.339489    0.390476